### PR TITLE
Add skeleton for ACC

### PR DESCRIPTION
**Pull request by aytekinar**

### CODE REVIEW

**Comment by aytekinar** [comment]
Do you think you can identify this system? Do you think I could prepare the data properly?

Btw, you might not be able to `Pkg.add("ODE")` on your local machine due to `Juno`. Try ssh'ing to T7600 and starting the notebooks there. `juliabox` should also work fine.

**Comment by neveritt** [comment]
I think the data is great :)
Hopefully I can identify the system. 

Can we add some random phases to the sinusoids? This way the data will look more random and we don't get the initial spike in the signals.

I'm thinking something like this:

```
immutable Sinosoid
    f::Vector
    δ::Vector
    
    (::Type{Sinosoid})(f::Vector) = new(f, 2π*rand(length(f)))
    (::Type{Sinosoid})() = new(logspace(-1,0,50), 2π*rand(50))
    (s::Sinosoid)(t::Real) = sum(map((f,t,δ)->sin(2π*f*t+δ), s.f, fill(t, size(s.f)), s.δ))
    (s::Sinosoid)(t::AbstractArray) = map(s, t)
end
```

**Comment by neveritt** [comment]
Btw, `ODE` worked on my home laptop, why don't it work on your local machine?

**Comment by aytekinar** [comment]
`ODE` works well (but `Pkg.checkout("ODE")` and `Pkg.update()` fails now).

I think I have fixed the data as per your request --- please let me know if you get the numbers correctly.

**Pull request merged**
